# Alpine Linux with OpenJDK JRE
FROM openjdk:8-jre-alpine
# copy fat WAR
COPY target/discovery-0.0.1-SNAPSHOT.jar /discovery-service.jar
# runs application
CMD ["/usr/bin/java", "-jar","/discovery-service.jar"]